---
format: gfm
title: "Tabletop ABM for Davis County, Utah"
---

This repository presents a tabletop agent-based model (ABM) for disease spread in Davis County, Utah. The model utilizes age mixing data to simulate disease transmission dynamics under various intervention scenarios, including isolation, quarantine, and post-exposure prophylaxis (PEP).

This is not a real situation and is intended for educational purposes only.

## Description of the model

The implemented model is a Susceptible Exposed Infectious Hospitalized Recovered (SEIRH) model with mixing and quarantine features. The model features what we call entities, which are subgroups of the population defined by age groups and schools. School-age agents are assigned to schools based on the population data, and the rest of the population is assigned to age groups. The mixing patterns are given by an age-based contact matrix based on the Polymod study.

The model features contact tracing, isolation of detected cases, and quarantine of contacts. Detection happens with uncertainty (80% success rate), and agents isolate and move to the quarantine states with certainty (for now). The model also allows for the implementation of post-exposure prophylaxis (PEP) for contacts of detected cases. The PEP is implemented as a baseline tool that reduces the probability of becoming infected and transmitting the disease.

To execute this model, it is recommended to run it in a high-performance computing environment due to its computational intensity, especially when simulating multiple scenarios. The model is fast, but the Davis county population is large (over 350,000), and running multiple simulations can be time-consuming on a standard personal computer.

The following diagram illustrates the compartments and transitions in the SEIRH model:

```mermaid
flowchart TB

    %% Disease progression states
    subgraph Main[Disease Progression]
        direction TB
        S[Susceptible]
        E[Exposed]
        In[Infected]
        H[Hospitalized]
        R[Recovered]
    end

    S --> E
    E --> In
    In --> H
    H --> R
    In --> R

    %% Quarantine states
    Dh[Detected<br>Hospitalized]
    Qs[Quarantined<br>Susceptible]
    Qe[Quarantined<br>Exposed]
    I[Isolated]
    Ir[Isolated<br>Recovered]

    %% Infected to
    In <==> I
    In --> Ir
    In --> Dh

    %% Isolated to
    I --> R
    I --> Ir
    I --> H
    I --> Dh

    %% Susceptible quarantined
    S <==> Qs

    %% Exposed
    E <==> Qe

    Qe --> I
    Qe --> In

    Dh --> R

    %% Isolated recovered
    Ir --> R
```


## Links to the scenarios

The following table links to the reports generated for each of the scenarios run for Davis County:

```{r}
#| label: listing
#| echo: false
fns <- list.files(path = "scenarios", pattern = "\\.md$", full.names = TRUE)

# Processing the names
scenarios <- data.frame(
  R0 = gsub(".+R0_([0-9.]+)_.*", "\\1", fns),
  Isolation = gsub(".+isolation_([A-Za-z]+)_.*", "\\1", fns),
  Quarantine = gsub(".+quarantine_([A-Za-z]+)(\\.|_).+", "\\1", fns),
  PEP = ifelse(grepl("_pep_yes", fns), "yes", "no"),
  Link = paste0("[View Report](", fns, ")")
)

# Sorting by R0, Isolation, Quarantine
scenarios <- scenarios[
  order(
    as.numeric(scenarios$R0),
    scenarios$Isolation,
    scenarios$Quarantine,
    scenarios$PEP
  ),
]

knitr::kable(
  scenarios,
  caption = "Links to the scenario reports for Davis County",
  row.names = FALSE
)
```

## Software

The simulations used the R package `epiworldR` version `r `packageVersion("epiworldR")``, which can be found at <https://github.com/UofUEpiBio/epiworldR>, and R version `r R.version.string`. 
